[package]
name = "merged_lands"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimalloc = { version = "0.1.29", default-features = false }
serde = { version = "1.0.139", features = ["derive"] }
bincode = "1.3.3"
bitflags = "1.3.2"
anymap = "0.12.1"
static_assertions = "1.1.0"
copyless = "0.1.5"
byteorder = "1.4.3"
image = "0.24.3"
num-traits = "0.2.15"
cismute = "0.1.2"
anyhow = "1.0.58"
itertools = "0.10.3"
filetime = "0.2.17"

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
default-features = false
features = ["esp"]  # add "nif" only if you need it